### ISSUE TITLE
The refactor branch code crashes after some time

### ISSUE THREAD

**Issue by vyi** [IshitaTakeshi/lsd_slam_noros#4]
Hi,

I am using the **refactor** branch to obtain the point cloud output.
I can build the `main_on_images` successfully and the program runs initially (processes many Images) and then crashes. See the attached log.

```
reading ../../../../June/dataset/data/sequence_30/images/00739.jpg
12.4671 % of points added
PublishKeyframe
reading ../../../../June/dataset/data/sequence_30/images/00740.jpg
Exporting pointcloud to output
12.4831 % of points added
PublishKeyframe
12.5046 % of points added
PublishKeyframe

Thread 1 "main_on_images" received signal SIGSEGV, Segmentation fault.
0x0000000000c60c16 in pcl::PCDWriter::writeASCII<pcl::PointXYZRGB> (this=0x7fffffffdb20, file_name="output", cloud=..., precision=8) at /usr/include/pcl-1.7/pcl/io/impl/pcd_io.hpp:580
580	            memcpy (&value, reinterpret_cast<const char*> (&cloud.points[i]) + fields[d].offset + c * sizeof (float), sizeof (float));
(gdb) bt
#0  0x0000000000c60c16 in pcl::PCDWriter::writeASCII<pcl::PointXYZRGB> (this=0x7fffffffdb20, file_name="output", cloud=..., precision=8) at /usr/include/pcl-1.7/pcl/io/impl/pcd_io.hpp:580
#1  0x0000000000c5d707 in pcl::PCDWriter::write<pcl::PointXYZRGB> (this=0x7fffffffdb20, file_name="output", cloud=..., binary=false) at /usr/include/pcl-1.7/pcl/io/pcd_io.h:449
#2  0x0000000000c5c3b9 in pcl::io::savePCDFile<pcl::PointXYZRGB> (file_name="output", cloud=..., binary_mode=false) at /usr/include/pcl-1.7/pcl/io/pcd_io.h:590
#3  0x0000000000c587c4 in lsd_slam::DebugOutput3DWrapper::savePointCloud (this=0x15bf3d0, filename="output") at /home/July/Milestone_2/lsd_slam_noros/apps/slam/DebugOutput3DWrapper.cpp:132
#4  0x0000000000c4f8a3 in main (argc=3, argv=0x7fffffffdf88) at /home/July/Milestone_2/lsd_slam_noros/apps/slam/main_on_images.cc:251

```

The log suggests the source of crash as *line 132* of DebugOutput3DWrapper.cpp file.  The following line:

`pcl::io::savePCDFile(filename, this->pointcloud);`

Why would a call to the pcl library i/o function `savePCDFile` cause crash ?
Any idea's? Did anyone else encounter this?

**Comment by vyi** [comment]
Hi,

I figured out that the debug build doesn't crash. I don't yet know the reason why it crashes with debug.
